Ignore display style to work on Android
conorhastings/react-native-syntax-highlighter pull request #2
Opened 2017-05-02 16:17 UTC by stefanoeb

Fixes #1

2017-05-02 16:23 UTC, conorhastings requested changes

2017-05-02 16:23 UTC, conorhastings commented on src/index.js
> +        return newStyle
can you add semicolon, i'll try to get an eslint or convert to prettier soon to avoid these annoyances

2017-05-02 18:59 UTC, stefanoeb commented on src/index.js
> +        return newStyle
yep, in a couple hours I'll send a fix

2017-05-03 11:50 UTC, conorhastings commented
sweet thanks

2017-05-03 11:50 UTC, merged

2017-05-03 11:52 UTC, conorhastings commented
published as `1.1.0`